@startuml
UserA -> "Fundable Token": orderFund
"Fundable Token" --> "Fund Agent": FundOrdered
"Fund Agent" -> "Fundable Token": processFund
"Fundable Token" --> "UserA": FundInProcess
"UserA funds" --> "Fund Agent": transfer funds
"Fund Agent" -> "Fundable Token": executeFund
"Fundable Token" --> UserA: FundExecuted
@enduml
